GET http://localhost:3000/states/

###

GET http://localhost:3000/states/8/

###


GET http://localhost:3000/districts/3/

###

DELETE http://localhost:3000/districts/322/

###



PUT http://localhost:3000/districts/322/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/4/stats/

###

GET http://localhost:3000/districts/4/details/